from django.db import models
from mongoengine import *

connect('wealth_management_indices')

class fundamentalportfolio(models.Model):
    COMPANY_CHOICES = (
    ('nifty50','Nifty 50'),
    ('nifty100', 'Nifty 100'),
    ('nifty200','Nifty 200'),
    ('nifty500','Nifty 500'),
    )
    
    PE_CHOICES = (
        ('Any','Any'),
        ('Trailing_P_E__lt=15', 'Low (<15)'),
        ('Trailing_P_E__lt=50', 'High (>50)'),
        ('u5','Under 5'),
        ('u10','Under 10'),
        ('u15','Under 15'),
        ('u20','Under 20'),
        ('u25','Under 25'),
        ('u30','Under 30'),
        ('u35','Under 35'),
        ('u40','Under 40'),
        ('u45','Under 45'),
        ('u50','Under 50'),
        ('o5','Over 5'),
        ('o10','Over 10'),
        ('o15','Under 15'),
        ('o20','Under 20'),
        ('o25','Under 25'),
        ('o30','Under 30'),
        ('035','Under 35'),
        ('o40','Under 40'),
        ('o45','Under 45'),
        ('o50','Under 50'),
    )
    PS_CHOICES = (
        ('Any','Any'),
        ('low1', 'Low (<1)'),
        ('high10', 'High (>10)'),
        ('u1','Under 1'),
        ('u2','Under 2'),
        ('u3','Under 3'),
        ('u5','Under 5'),
        ('u6','Under 6'),
        ('u7','Under 7'),
        ('u8','Under 8'),
        ('u9','Under 9'),
        ('u10','Under 10'),
        ('o1','over 1'),
        ('o2','over 2'),
        ('o3','over 3'),
        ('o4','over 5'),
        ('o5','over 6'),
        ('o6','over 7'),
        ('o7','over 8'),
        ('o8','over 9'),
        ('o9','over 10'),
        ('custom','Custom (Elite Only)'),
    )
    PEG_CHOICES = (
        ('Any','Any'),
        ('low1', 'Low (<1)'),
        ('high2', 'High (>2)'),
        ('u1','Under 1'),
        ('u2','Under 2'),
        ('u3','Under 3'),
        ('o1','Over 1'),
        ('o2','Over 2'),
        ('o3','Under 3'),
        ('custom','Custom (Elite Only)'),
    )
    PB_CHOICES = (
        ('Any','Any'),
        ('low1', 'Low (<1)'),
        ('high5', 'High (>5)'),
        ('u1','Under 1'),
        ('u2','Under 2'),
        ('u3','Under 3'),
        ('u5','Under 5'),
        ('u6','Under 6'),
        ('u7','Under 7'),
        ('u8','Under 8'),
        ('u9','Under 9'),
        ('u10','Under 10'),
        ('o1','over 1'),
        ('o2','over 2'),
        ('o3','over 3'),
        ('o4','over 5'),
        ('o5','over 6'),
        ('o6','over 7'),
        ('o7','over 8'),
        ('o8','over 9'),
        ('o9','over 10'),
        ('custom','Custom (Elite Only)'),
    )
    PRICE_CASH_CHOICES = (
        ('Any','Any'),
        ('low3', 'Low (<3)'),
        ('high50', 'High (>50)'),
        ('u1','Under 1'),
        ('u2','Under 2'),
        ('u3','Under 3'),
        ('u5','Under 5'),
        ('u6','Under 6'),
        ('u7','Under 7'),
        ('u8','Under 8'),
        ('u9','Under 9'),
        ('u10','Under 10'),
        ('o1','over 1'),
        ('o2','over 2'),
        ('o3','over 3'),
        ('o4','over 4'),
        ('o5','over 5'),
        ('o6','over 6'),
        ('o7','over 7'),
        ('o8','over 8'),
        ('o8','over 9'),
        ('o10','over 10'),
        ('o20','over 20'),
        ('o30','over 30'),
        ('o40','over 40'),
        ('o50','over 50'),
        ('custom','Custom (Elite Only)'),
    )
    PRICE_FREE_CASH_FLOW_CHOICES = (
        ('Any','Any'),
        ('low', 'Low (<3)'),
        ('high', 'High (>50)'),
        ('u5','Under 5'),
        ('u10','Under 10'),
    	 ('u15','Under 15'),
		 ('u20','Under 20'),
		 ('u25','Under 25'),
		 ('u30','Under 30'),
		 ('u35','Under 35'),
		 ('u40','Under 40'),
		 ('u45','Under 45'),
		 ('u50','Under 50'),
		 ('u60','Under 60'),
		 ('u70','Under 70'),
		 ('u80','Under 80'),
		 ('u90','Under 90'),
		 ('u100','Under 100'),
		 ('o5','Over 5'),
		 ('o10','Over 10'),
		 ('o15','Over 15'),
		 ('o20','Over 20'),
		 ('o25','Over 25'),
		 ('o30','Over 30'),
		 ('o35','Over 35'),
		 ('o40','Over 40'),
		 ('o45','Over 45'),
		 ('o50','Over 50'),
		 ('o60','Over 60'),
		 ('o70','Over 70'),
		 ('o80','Over 80'),
		 ('o90','Over 90'),
		 ('o100','Over 100'),
		 ('range','Custom (Elite only)'),    
    )
    EPS_GROWTH_THIS_YEAR_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),
    )
    EPS_GROWTH_NEXT_YEAR_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),
    )
    EPS_GROWTH_PAST_5_YEARS_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),   
    )
    EPS_GROWTH_NEXT_5_YEARS_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),  
    )
    SALES_GROWTH_PAST_5_YEARS_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),   
    )
    EPS_GROWTH_QTR_OVER_QTR_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),     
    )
    SALES_GROWTH_QTR_OVER_QTR_CHOICES = (
       ('Any','Any'),
       ('neg','Negative (<0%)'),
       ('pos','Positive (>0%)'),
       ('poslow','Positive Low (0-10%)'),
       ('high','High (>25%)'),
       ('u5','Under 5%'),
       ('u10','Under 10%'),
       ('u15','Under 15%'),
       ('u20','Under 20%'),
       ('u25','Under 25%'),
       ('u30','Under 30%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('range','Custom (Elite only)'),  
    )
    RETURN_ON_ASSETS_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('verypos','Very Positive (>15%)'),
       ('veryneg','Very Negative (<-15%)'),
       ('u-50','Under -50%'),
       ('u-45','Under -45%'),
       ('u-40','Under -40%'),
       ('u-35','Under -35%'),
       ('u-30','Under -30%'),
       ('u-25','Under -25%'),
       ('u-20','Under -20%'),
       ('u-15','Under -15%'),
       ('u-10','Under -10%'),
       ('u-5','Under -5%'),
       ('o5','Over +5%'),
       ('o10','Over +10%'),
       ('o15','Over +15%'),
       ('o20','Over +20%'),
       ('o25','Over +25%'),
       ('o30','Over +30%'),
       ('o35','Over +35%'),
       ('o40','Over +40%'),
       ('o45','Over +45%'),
       ('o50','Over +50%'),
       ('range','Custom (Elite only)'),
    )
    RETURN_ON_EQUITY_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('verypos','Very Positive (>15%)'),
       ('veryneg','Very Negative (<-15%)'),
       ('u-50','Under -50%'),
       ('u-45','Under -45%'),
       ('u-40','Under -40%'),
       ('u-35','Under -35%'),
       ('u-30','Under -30%'),
       ('u-25','Under -25%'),
       ('u-20','Under -20%'),
       ('u-15','Under -15%'),
       ('u-10','Under -10%'),
       ('u-5','Under -5%'),
       ('o5','Over +5%'),
       ('o10','Over +10%'),
       ('o15','Over +15%'),
       ('o20','Over +20%'),
       ('o25','Over +25%'),
       ('o30','Over +30%'),
       ('o35','Over +35%'),
       ('o40','Over +40%'),
       ('o45','Over +45%'),
       ('o50','Over +50%'),
       ('range','Custom (Elite only)'),
    )
    RETURN_ON_INVESTMENT_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('verypos','Very Positive (>15%)'),
       ('veryneg','Very Negative (<-15%)'),
       ('u-50','Under -50%'),
       ('u-45','Under -45%'),
       ('u-40','Under -40%'),
       ('u-35','Under -35%'),
       ('u-30','Under -30%'),
       ('u-25','Under -25%'),
       ('u-20','Under -20%'),
       ('u-15','Under -15%'),
       ('u-10','Under -10%'),
       ('u-5','Under -5%'),
       ('o5','Over +5%'),
       ('o10','Over +10%'),
       ('o15','Over +15%'),
       ('o20','Over +20%'),
       ('o25','Over +25%'),
       ('o30','Over +30%'),
       ('o35','Over +35%'),
       ('o40','Over +40%'),
       ('o45','Over +45%'),
       ('o50','Over +50%'),
       ('range','Custom (Elite only)'),
    )
    CURRENT_RATIO_CHOICES = (
       ('Any','Any'),
       ('high','High (>3)'),
       ('low','Low (<1)'),
       ('u1','Under 1'),
       ('u0.5','Under 0.5'),
       ('o0.5','Over 0.5'),
       ('o1','Over 1'),
       ('o1.5','Over 1.5'),
       ('o2','Over 2'),
       ('o3','Over 3'),
       ('o4','Over 4'),
       ('o5','Over 5'),
       ('o10','Over 10'),
       ('range','Custom (Elite only)'),
    )
    QUICK_RATIO_CHOICES = (
       ('Any','Any'),
       ('high','High (>3)'),
       ('low','Low (<1)'),
       ('u1','Under 1'),
       ('u0.5','Under 0.5'),
       ('o0.5','Over 0.5'),
       ('o1','Over 1'),
       ('o1.5','Over 1.5'),
       ('o2','Over 2'),
       ('o3','Over 3'),
       ('o4','Over 4'),
       ('o5','Over 5'),
       ('o10','Over 10'),
       ('range','Custom (Elite only)'),
    )
    LT_DEBT_EQUITY_CHOICES = (
       ('Any','Any'),
       ('high','High (>0.5)'),
       ('low','Low (<0.1)'),
       ('u1','Under 1'),
       ('u0.9','Under 0.9'),
       ('u0.8','Under 0.8'),
       ('u0.7','Under 0.7'),
       ('u0.6','Under 0.6'),
       ('u0.5','Under 0.5'),
       ('u0.4','Under 0.4'),
       ('u0.3','Under 0.3'),
       ('u0.2','Under 0.2'),
       ('u0.1','Under 0.1'),
       ('o0.1','Over 0.1'),
       ('o0.2','Over 0.2'),
       ('o0.3','Over 0.3'),
       ('o0.4','Over 0.4'),
       ('o0.5','Over 0.5'),
       ('o0.6','Over 0.6'),
       ('o0.7','Over 0.7'),
       ('o0.8','Over 0.8'),
       ('o0.9','Over 0.9'),
       ('o1','Over 1'),
       ('frange','Custom (Elite only)'),
    )
    DEBT_EQUITY_CHOICES = (
       ('Any','Any'),
       ('high','High (>0.5)'),
       ('low','Low (<0.1)'),
       ('u1','Under 1'),
       ('u0.9','Under 0.9'),
       ('u0.8','Under 0.8'),
       ('u0.7','Under 0.7'),
       ('u0.6','Under 0.6'),
       ('u0.5','Under 0.5'),
       ('u0.4','Under 0.4'),
       ('u0.3','Under 0.3'),
       ('u0.2','Under 0.2'),
       ('u0.1','Under 0.1'),
       ('o0.1','Over 0.1'),
       ('o0.2','Over 0.2'),
       ('o0.3','Over 0.3'),
       ('o0.4','Over 0.4'),
       ('o0.5','Over 0.5'),
       ('o0.6','Over 0.6'),
       ('o0.7','Over 0.7'),
       ('o0.8','Over 0.8'),
       ('o0.9','Over 0.9'),
       ('o1','Over 1'),
       ('frange','Custom (Elite only)'),
    )
    GROSS_MARGIN_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('high','High (>50%)'),
       ('u90','Under 90%'),
       ('u80','Under 80%'),
       ('u70','Under 70%'),
       ('u60','Under 60%'),
       ('u50','Under 50%'),
       ('u45','Under 45%'),
       ('u40','Under 40%'),
       ('u35','Under 35%'),
       ('u30','Under 30%'),
       ('u25','Under 25%'),
       ('u20','Under 20%'),
       ('u15','Under 15%'),
       ('u10','Under 10%'),
       ('u5','Under 5%'),
       ('u0','Under 0%'),
       ('u-10','Under -10%'),
       ('u-20','Under -20%'),
       ('u-30','Under -30%'),
       ('u-50','Under -50%'),
       ('u-70','Under -70%'),
       ('u-100','Under -100%'),
       ('o0','Over 0%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('o35','Over 35%'),
       ('o40','Over 40%'),
       ('o45','Over 45%'),
       ('o50','Over 50%'),
       ('o60','Over 60%'),
       ('o70','Over 70%'),
       ('o80','Over 80%'),
       ('o90','Over 90%'),
       ('range','Custom (Elite only)'),
    )
    OPERATING_MARGIN_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('veryneg','Very Negative (<-20%)'),
       ('high','High (>25%)'),
       ('u90','Under 90%'),
       ('u80','Under 80%'),
       ('u70','Under 70%'),
       ('u60','Under 60%'),
       ('u50','Under 50%'),
       ('u45','Under 45%'),
       ('u40','Under 40%'),
       ('u35','Under 35%'),
       ('u30','Under 30%'),
       ('u25','Under 25%'),
       ('u20','Under 20%'),
       ('u15','Under 15%'),
       ('u10','Under 10%'),
       ('u5','Under 5%'),
       ('u0','Under 0%'),
       ('u-10','Under -10%'),
       ('u-20','Under -20%'),
       ('u-30','Under -30%'),
       ('u-50','Under -50%'),
       ('u-70','Under -70%'),
       ('u-100','Under -100%'),
       ('o0','Over 0%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('o35','Over 35%'),
       ('o40','Over 40%'),
       ('o45','Over 45%'),
       ('o50','Over 50%'),
       ('o60','Over 60%'),
       ('o70','Over 70%'),
       ('o80','Over 80%'),
       ('o90','Over 90%'),
       ('range','Custom (Elite only)'),
    )
    NET_PROFIT_MARGIN_CHOICES = (
       ('Any','Any'),
       ('pos','Positive (>0%)'),
       ('neg','Negative (<0%)'),
       ('veryneg','Very Negative (<-20%)'),
       ('high','High (>20%)'),
       ('u90','Under 90%'),
       ('u80','Under 80%'),
       ('u70','Under 70%'),
       ('u60','Under 60%'),
       ('u50','Under 50%'),
       ('u45','Under 45%'),
       ('u40','Under 40%'),
       ('u35','Under 35%'),
       ('u30','Under 30%'),
       ('u25','Under 25%'),
       ('u20','Under 20%'),
       ('u15','Under 15%'),
       ('u10','Under 10%'),
       ('u5','Under 5%'),
       ('u0','Under 0%'),
       ('u-10','Under -10%'),
       ('u-20','Under -20%'),
       ('u-30','Under -30%'),
       ('u-50','Under -50%'),
       ('u-70','Under -70%'),
       ('u-100','Under -100%'),
       ('o0','Over 0%'),
       ('o5','Over 5%'),
       ('o10','Over 10%'),
       ('o15','Over 15%'),
       ('o20','Over 20%'),
       ('o25','Over 25%'),
       ('o30','Over 30%'),
       ('o35','Over 35%'),
       ('o40','Over 40%'),
       ('o45','Over 45%'),
       ('o50','Over 50%'),
       ('o60','Over 60%'),
       ('o70','Over 70%'),
       ('o80','Over 80%'),
       ('o90','Over 90%'),
       ('range','Custom (Elite only)'),
    )
    PAYOUT_RATIO_CHOICES = (
       ('Any','Any'),
       ('none','None (0%)'),
       ('pos','Positive (>0%)'),
       ('low','Low (<20%)'),
       ('high','High (>50%)'),
       ('o0','Over 0%'),
       ('o10','Over 10%'),
       ('o20','Over 20%'),
       ('o30','Over 30%'),
       ('o40','Over 40%'),
       ('o50','Over 50%'),
       ('o60','Over 60%'),
       ('o70','Over 70%'),
       ('o80','Over 80%'),
       ('o90','Over 90%'),
       ('o100','Over 100%'),
       ('u10','Under 10%'),
       ('u20','Under 20%'),
       ('u30','Under 30%'),
       ('u40','Under 40%'),
       ('u50','Under 50%'),
       ('u60','Under 60%'),
       ('u70','Under 70%'),
       ('u80','Under 80%'),
       ('u90','Under 90%'),
       ('u100','Under 100%'),
       ('range','Custom (Elite only)'),
    )
    INSIDER_OWNERSHIP_CHOICES = (
       ('Any','Any'),
       ('low','Low (<5%)'),
       ('high','High (>30%)'),
       ('veryhigh','Very High (>50%)'),
       ('o10','Over 10%'),
       ('o20','Over 20%'),
       ('o30','Over 30%'),
       ('o40','Over 40%'),
       ('o50','Over 50%'),
       ('o60','Over 60%'),
       ('o70','Over 70%'),
       ('o80','Over 80%'),
       ('o90','Over 90%'),
       ('range','Custom (Elite only)'),
    )
    INSIDER_TRANSACTIONS_CHOICES = (
        ('Any','Any'),
        ('veryneg','Very Negative (<20%)'),
        ('neg','Negative (<0%)'),
        ('pos','Positive (>0%)'),
        ('verypos','Very Positive (>20%)'),
        ('u-90','Under -90%'),
        ('u-80','Under -80%'),
        ('u-70','Under -70%'),
        ('u-60','Under -60%'),
        ('u-50','Under -50%'),
        ('u-45','Under -45%'),
        ('u-40','Under -40%'),
        ('u-35','Under -35%'),
        ('u-30','Under -30%'),
        ('u-25','Under -25%'),
        ('u-20','Under -20%'),
        ('u-15','Under -15%'),
        ('u-10','Under -10%'),
        ('u-5','Under -5%'),
        ('o5','Over +5%'),
        ('o10','Over +10%'),
        ('o15','Over +15%'),
        ('o20','Over +20%'),
        ('o25','Over +25%'),
        ('o30','Over +30%'),
        ('o35','Over +35%'),
        ('o40','Over +40%'),
        ('o45','Over +45%'),
        ('o50','Over +50%'),
        ('o60','Over +60%'),
        ('o70','Over +70%'),
        ('o80','Over +80%'),
        ('o90','Over +90%'),      
        ('range','Custom (Elite only)'),
    )
    INSTITUTIONAL_OWNERSHIP_CHOICES = (
        ('Any','Any'),
        ('low','Low (<5%)'),
        ('high','High (>90%)'),
        ('u90','Under 90%'),
        ('u80','Under 80%'),
        ('u70','Under 70%'),
        ('u60','Under 60%'),
        ('u50','Under 50%'),
        ('u40','Under 40%'),
        ('u30','Under 30%'),
        ('u20','Under 20%'),
        ('u10','Under 10%'),
        ('o10','Over 10%'),
        ('o20','Over 20%'),
        ('o30','Over 30%'),
        ('o40','Over 40%'),
        ('o50','Over 50%'),
        ('o60','Over 60%'),
        ('o70','Over 70%'),
        ('o80','Over 80%'),
        ('o90','Over 90%'),
        ('range','Custom (Elite only)'),    
    )
    companyType= models.CharField(max_length=100,choices=COMPANY_CHOICES, default='nifty50' )
    Trailing_P_E=models.CharField(max_length=100,choices=PE_CHOICES, default='Any')
    Forward_P_E=models.CharField(max_length=100,choices=PE_CHOICES, default='Any')
    PEG=models.CharField(max_length=100,choices=PEG_CHOICES, default='Any')
    PS=models.CharField(max_length=100,choices=PS_CHOICES, default='Any')
    PB=models.CharField(max_length=100,choices=PB_CHOICES, default='Any')
    Price_Cash=models.CharField(max_length=100,choices=PRICE_CASH_CHOICES, default='Any')
    Ticker=models.CharField(max_length=100)
    Price_Free_Cash_Flow=models.CharField(max_length=100,choices=PRICE_FREE_CASH_FLOW_CHOICES, default='Any')
    EPS_growth_this_year=models.CharField(max_length=100,choices=EPS_GROWTH_THIS_YEAR_CHOICES, default='Any')
    EPS_growth_next_year=models.CharField(max_length=100,choices=EPS_GROWTH_NEXT_YEAR_CHOICES, default='Any')
    EPS_growth_past_5_years=models.CharField(max_length=100,choices=EPS_GROWTH_PAST_5_YEARS_CHOICES, default='Any')
    EPS_growth_next_5_years=models.CharField(max_length=100,choices=EPS_GROWTH_NEXT_5_YEARS_CHOICES, default='Any')
    Sales_growth_past_5_years=models.CharField(max_length=100,choices=SALES_GROWTH_PAST_5_YEARS_CHOICES, default='Any')
    EPS_growth_qtr_over_qtr=models.CharField(max_length=100,choices=EPS_GROWTH_QTR_OVER_QTR_CHOICES, default='Any')
    Sales_growth_qtr_over_qtr=models.CharField(max_length=100,choices=SALES_GROWTH_QTR_OVER_QTR_CHOICES, default='Any')
    Return_on_Assets=models.CharField(max_length=100,choices=RETURN_ON_ASSETS_CHOICES, default='Any')
    Return_on_Equity=models.CharField(max_length=100,choices=RETURN_ON_EQUITY_CHOICES, default='Any')
    Return_on_Investment=models.CharField(max_length=100,choices=RETURN_ON_INVESTMENT_CHOICES, default='Any')
    Current_Ratio=models.CharField(max_length=100,choices=CURRENT_RATIO_CHOICES, default='Any')
    Quick_Ratio=models.CharField(max_length=100,choices=QUICK_RATIO_CHOICES, default='Any')
    Lt_Debt_Equity=models.CharField(max_length=100,choices=LT_DEBT_EQUITY_CHOICES, default='Any')
    Debt_Equity=models.CharField(max_length=100,choices=DEBT_EQUITY_CHOICES, default='Any')
    Gross_Margin=models.CharField(max_length=100,choices=GROSS_MARGIN_CHOICES, default='Any')
    Operating_Margin=models.CharField(max_length=100,choices=OPERATING_MARGIN_CHOICES, default='Any')
    Net_Profit_Margin=models.CharField(max_length=100,choices=NET_PROFIT_MARGIN_CHOICES, default='Any')
    Payout_Ratio=models.CharField(max_length=100,choices=PAYOUT_RATIO_CHOICES, default='Any')
    Insider_Ownership=models.CharField(max_length=100,choices=INSIDER_OWNERSHIP_CHOICES, default='Any')
    Insider_Transactions=models.CharField(max_length=100,choices=INSIDER_TRANSACTIONS_CHOICES, default='Any')
    Institutional_Ownership=models.CharField(max_length=100,choices=INSTITUTIONAL_OWNERSHIP_CHOICES, default='Any')
    
    
    
