from django.db import models
from mongoengine import *

connect('wealth_management_indices')

class fundamentalportfolio(models.Model):
    COMPANY_CHOICES = (
    ('nifty50','Nifty 50'),
    ('nifty100', 'Nifty 100'),
    ('nifty200','Nifty 200'),
    ('nifty500','Nifty 500'),
    )
    
    PE_CHOICES = (
        ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),
    )
    PS_CHOICES = (
        ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),
    )
    BETA_CHOICES = (
        ('Any','Any'),
        ('lt_0.5', 'Low (<0.5)'),
        ('gt_0.5', 'High (>0.5)'),
        ('lt_0.7','Under 0.7'),
        ('lt_1','Under 1'),
        ('lt_1.5','Under 1.5'),
        ('lt_2','Under 2'),
        ('gt_0.7','Over 0.7'),
        ('gt_1','Over 1'),
        ('gt_1.5','Over 1.5'),
        ('gt_2','Over 2'),
    )
    PEG_CHOICES = (
       ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),
    )
    PB_CHOICES = (
        ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),
    )
    PRICE_CASH_CHOICES = (
       ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),
    )
    PRICE_FREE_CASH_FLOW_CHOICES = (
        ('Any','Any'),
        ('lt_15', 'Low (<15)'),
        ('gt_50', 'High (>50)'),
        ('lt_5','Under 5'),
        ('lt_10','Under 10'),
        ('lt_25','Under 25'),
        ('lt_45','Under 45'),
        ('gt_5','Over 5'),
        ('gt_10','Over 10'),
        ('gt_15','Over 15'),
        ('gt_25','Over 25'),
        ('gt_35','Over 35'),
        ('gt_45','Over 45'),    
    )
    EPS_GROWTH_THIS_YEAR_CHOICES = (
        ('Any','Any'),
        ('lt_15', 'Low (<15%)'),
        ('gt_50', 'High (>50%)'),
        ('lt_5','Under 5%'),
        ('lt_10','Under 10%'),
        ('lt_25','Under 25%'),
        ('lt_45','Under 45%'),
        ('gt_5','Over 5%'),
        ('gt_10','Over 10%'),
        ('gt_15','Over 15%'),
        ('gt_25','Over 25%'),
        ('gt_35','Over 35%'),
        ('gt_45','Over 45%'),
    )
    RETURN_ON_ASSETS_CHOICES = (
       ('Any','Any'),
        ('lt_15', 'Low (<15%)'),
        ('gt_50', 'High (>50%)'),
        ('lt_5','Under 5%'),
        ('lt_10','Under 10%'),
        ('lt_25','Under 25%'),
        ('lt_45','Under 45%'),
        ('gt_5','Over 5%'),
        ('gt_10','Over 10%'),
        ('gt_15','Over 15%'),
        ('gt_25','Over 25%'),
        ('gt_35','Over 35%'),
        ('gt_45','Over 45%'),
    )
    RETURN_ON_EQUITY_CHOICES = (
       ('Any','Any'),
        ('lt_15', 'Low (<15%)'),
        ('gt_50', 'High (>50%)'),
        ('lt_5','Under 5%'),
        ('lt_10','Under 10%'),
        ('lt_25','Under 25%'),
        ('lt_45','Under 45%'),
        ('gt_5','Over 5%'),
        ('gt_10','Over 10%'),
        ('gt_15','Over 15%'),
        ('gt_25','Over 25%'),
        ('gt_35','Over 35%'),
        ('gt_45','Over 45%'),
    )
    CURRENT_RATIO_CHOICES = (
       ('Any','Any'),
       ('gt_3','High (>3)'),
       ('lt_1','Low (<1)'),
       ('lt_0.5','Under 0.5'),
       ('gt_0','Over 0.5'),
       ('gt_1','Over 1'),
       ('gt_1.5','Over 1.5'),
       ('gt_2','Over 2'),
       ('gt_3','Over 3'),
       ('gt_4','Over 4'),
       ('gt_5','Over 5'),
       ('gt_10','Over 10'),
    )
    QUICK_RATIO_CHOICES = (
       ('Any','Any'),
       ('gt_3','High (>3)'),
       ('lt_1','Low (<1)'),
       ('lt_0.5','Under 0.5'),
       ('gt_0','Over 0.5'),
       ('gt_1','Over 1'),
       ('gt_1.5','Over 1.5'),
       ('gt_2','Over 2'),
       ('gt_3','Over 3'),
       ('gt_4','Over 4'),
       ('gt_5','Over 5'),
       ('gt_10','Over 10'),
    )
    LT_DEBT_EQUITY_CHOICES = (
       ('Any','Any'),
       ('gt_0.5','High (>0.5)'),
       ('lt_0.1','Low (<0.1)'),
       ('lt_1','Under 1'),
       ('lt_0.9','Under 0.9'),
       ('lt_0.8','Under 0.8'),
       ('lt_0.7','Under 0.7'),
       ('lt_0.6','Under 0.6'),
       ('lt_0.5','Under 0.5'),
       ('lt_0.4','Under 0.4'),
       ('lt_0.3','Under 0.3'),
       ('lt_0.2','Under 0.2'),
       ('lt_0.1','Under 0.1'),
       ('gt_0.1','Over 0.1'),
       ('gt_0.2','Over 0.2'),
       ('gt_0.3','Over 0.3'),
       ('gt_0.4','Over 0.4'),
       ('gt_0.5','Over 0.5'),
       ('gt_0.6','Over 0.6'),
       ('gt_0.7','Over 0.7'),
       ('gt_0.8','Over 0.8'),
       ('gt_0.9','Over 0.9'),
       ('gt_1','Over 1'),
    )
    DEBT_EQUITY_CHOICES = (
       ('Any','Any'),
       ('gt_0.5','High (>0.5)'),
       ('lt_0.1','Low (<0.1)'),
       ('lt_1','Under 1'),
       ('lt_0.9','Under 0.9'),
       ('lt_0.8','Under 0.8'),
       ('lt_0.7','Under 0.7'),
       ('lt_0.6','Under 0.6'),
       ('lt_0.5','Under 0.5'),
       ('lt_0.4','Under 0.4'),
       ('lt_0.3','Under 0.3'),
       ('lt_0.2','Under 0.2'),
       ('lt_0.1','Under 0.1'),
       ('gt_0.1','Over 0.1'),
       ('gt_0.2','Over 0.2'),
       ('gt_0.3','Over 0.3'),
       ('gt_0.4','Over 0.4'),
       ('gt_0.5','Over 0.5'),
       ('gt_0.6','Over 0.6'),
       ('gt_0.7','Over 0.7'),
       ('gt_0.8','Over 0.8'),
       ('gt_0.9','Over 0.9'),
       ('gt_1','Over 1'),
    )
    GROSS_MARGIN_CHOICES = (
       ('Any','Any'),
       ('gt_0','Positive (>0%)'),
       ('lt_0','Negative (<0%)'),
       ('gt_50','High (>50%)'),
       ('lt_90','Under 90%'),
       ('lt_80','Under 80%'),
       ('lt_70','Under 70%'),
       ('lt_60','Under 60%'),
       ('lt_50','Under 50%'),
       ('lt_45','Under 45%'),
       ('lt_40','Under 40%'),
       ('lt_35','Under 35%'),
       ('lt_30','Under 30%'),
       ('lt_25','Under 25%'),
       ('lt_20','Under 20%'),
       ('lt_15','Under 15%'),
       ('lt_10','Under 10%'),
       ('lt_5','Under 5%'),
       ('gt_10','Over 10%'),
       ('gt_15','Over 15%'),
       ('gt_20','Over 20%'),
       ('gt_25','Over 25%'),
       ('gt_30','Over 30%'),
       ('gt_35','Over 35%'),
       ('gt_40','Over 40%'),
       ('gt_45','Over 45%'),
       ('gt_50','Over 50%'),
       ('gt_60','Over 60%'),
       ('gt_70','Over 70%'),
       ('gt_80','Over 80%'),
       ('gt_90','Over 90%'),
    )
    NET_PROFIT_MARGIN_CHOICES = (
       ('Any','Any'),
       ('gt_0','Positive (>0%)'),
       ('lt_0','Negative (<0%)'),
       ('gt_50','High (>50%)'),
       ('lt_90','Under 90%'),
       ('lt_80','Under 80%'),
       ('lt_70','Under 70%'),
       ('lt_60','Under 60%'),
       ('lt_50','Under 50%'),
       ('lt_45','Under 45%'),
       ('lt_40','Under 40%'),
       ('lt_35','Under 35%'),
       ('lt_30','Under 30%'),
       ('lt_25','Under 25%'),
       ('lt_20','Under 20%'),
       ('lt_15','Under 15%'),
       ('lt_10','Under 10%'),
       ('lt_5','Under 5%'),
       ('gt_10','Over 10%'),
       ('gt_15','Over 15%'),
       ('gt_20','Over 20%'),
       ('gt_25','Over 25%'),
       ('gt_30','Over 30%'),
       ('gt_35','Over 35%'),
       ('gt_40','Over 40%'),
       ('gt_45','Over 45%'),
       ('gt_50','Over 50%'),
       ('gt_60','Over 60%'),
       ('gt_70','Over 70%'),
       ('gt_80','Over 80%'),
       ('gt_90','Over 90%'),
    )
    PAYOUT_RATIO_CHOICES = (
       ('Any','Any'),
       ('gt_0','Positive (>0%)'),
       ('lt_0','Negative (<0%)'),
       ('gt_50','High (>50%)'),
       ('lt_90','Under 90%'),
       ('lt_80','Under 80%'),
       ('lt_70','Under 70%'),
       ('lt_60','Under 60%'),
       ('lt_50','Under 50%'),
       ('lt_45','Under 45%'),
       ('lt_40','Under 40%'),
       ('lt_35','Under 35%'),
       ('lt_30','Under 30%'),
       ('lt_25','Under 25%'),
       ('lt_20','Under 20%'),
       ('lt_15','Under 15%'),
       ('lt_10','Under 10%'),
       ('lt_5','Under 5%'),
       ('gt_10','Over 10%'),
       ('gt_15','Over 15%'),
       ('gt_20','Over 20%'),
       ('gt_25','Over 25%'),
       ('gt_30','Over 30%'),
       ('gt_35','Over 35%'),
       ('gt_40','Over 40%'),
       ('gt_45','Over 45%'),
       ('gt_50','Over 50%'),
       ('gt_60','Over 60%'),
       ('gt_70','Over 70%'),
       ('gt_80','Over 80%'),
       ('gt_90','Over 90%'),
      )
    INSIDER_OWNERSHIP_CHOICES = (
       ('Any','Any'),
       ('gt_0','Positive (>0%)'),
       ('lt_0','Negative (<0%)'),
       ('gt_50','High (>50%)'),
       ('lt_90','Under 90%'),
       ('lt_80','Under 80%'),
       ('lt_70','Under 70%'),
       ('lt_60','Under 60%'),
       ('lt_50','Under 50%'),
       ('lt_45','Under 45%'),
       ('lt_40','Under 40%'),
       ('lt_35','Under 35%'),
       ('lt_30','Under 30%'),
       ('lt_25','Under 25%'),
       ('lt_20','Under 20%'),
       ('lt_15','Under 15%'),
       ('lt_10','Under 10%'),
       ('lt_5','Under 5%'),
       ('gt_10','Over 10%'),
       ('gt_15','Over 15%'),
       ('gt_20','Over 20%'),
       ('gt_25','Over 25%'),
       ('gt_30','Over 30%'),
       ('gt_35','Over 35%'),
       ('gt_40','Over 40%'),
       ('gt_45','Over 45%'),
       ('gt_50','Over 50%'),
       ('gt_60','Over 60%'),
       ('gt_70','Over 70%'),
       ('gt_80','Over 80%'),
       ('gt_90','Over 90%'),
    )
    INSTITUTIONAL_OWNERSHIP_CHOICES = (
       ('Any','Any'),
       ('gt_0','Positive (>0%)'),
       ('lt_0','Negative (<0%)'),
       ('gt_50','High (>50%)'),
       ('lt_90','Under 90%'),
       ('lt_80','Under 80%'),
       ('lt_70','Under 70%'),
       ('lt_60','Under 60%'),
       ('lt_50','Under 50%'),
       ('lt_45','Under 45%'),
       ('lt_40','Under 40%'),
       ('lt_35','Under 35%'),
       ('lt_30','Under 30%'),
       ('lt_25','Under 25%'),
       ('lt_20','Under 20%'),
       ('lt_15','Under 15%'),
       ('lt_10','Under 10%'),
       ('lt_5','Under 5%'),
       ('gt_10','Over 10%'),
       ('gt_15','Over 15%'),
       ('gt_20','Over 20%'),
       ('gt_25','Over 25%'),
       ('gt_30','Over 30%'),
       ('gt_35','Over 35%'),
       ('gt_40','Over 40%'),
       ('gt_45','Over 45%'),
       ('gt_50','Over 50%'),
       ('gt_60','Over 60%'),
       ('gt_70','Over 70%'),
       ('gt_80','Over 80%'),
       ('gt_90','Over 90%'),    
    )
    companyType= models.CharField(max_length=100,choices=COMPANY_CHOICES, default='nifty50' )
    Trailing_P_E=models.CharField(max_length=100,choices=PE_CHOICES, default='Any')
    Forward_P_E=models.CharField(max_length=100,choices=PE_CHOICES, default='Any')
    Beta=models.CharField(max_length=100,choices=BETA_CHOICES, default='Any')
    PEG=models.CharField(max_length=100,choices=PEG_CHOICES, default='Any')
    PS=models.CharField(max_length=100,choices=PS_CHOICES, default='Any')
    PB=models.CharField(max_length=100,choices=PB_CHOICES, default='Any')
    Price_Cash=models.CharField(max_length=100,choices=PRICE_CASH_CHOICES, default='Any')
    Ticker=models.CharField(max_length=100)
    Price_Free_Cash_Flow=models.CharField(max_length=100,choices=PRICE_FREE_CASH_FLOW_CHOICES, default='Any')
    EPS_growth_this_year=models.CharField(max_length=100,choices=EPS_GROWTH_THIS_YEAR_CHOICES, default='Any')
    Return_on_Assets=models.CharField(max_length=100,choices=RETURN_ON_ASSETS_CHOICES, default='Any')
    Return_on_Equity=models.CharField(max_length=100,choices=RETURN_ON_EQUITY_CHOICES, default='Any')
    Current_Ratio=models.CharField(max_length=100,choices=CURRENT_RATIO_CHOICES, default='Any')
    Quick_Ratio=models.CharField(max_length=100,choices=QUICK_RATIO_CHOICES, default='Any')
    Lt_Debt_Equity=models.CharField(max_length=100,choices=LT_DEBT_EQUITY_CHOICES, default='Any')
    Debt_Equity=models.CharField(max_length=100,choices=DEBT_EQUITY_CHOICES, default='Any')
    Gross_Margin=models.CharField(max_length=100,choices=GROSS_MARGIN_CHOICES, default='Any')
    Net_Profit_Margin=models.CharField(max_length=100,choices=NET_PROFIT_MARGIN_CHOICES, default='Any')
    Payout_Ratio=models.CharField(max_length=100,choices=PAYOUT_RATIO_CHOICES, default='Any')
    Insider_Ownership=models.CharField(max_length=100,choices=INSIDER_OWNERSHIP_CHOICES, default='Any')
    Institutional_Ownership=models.CharField(max_length=100,choices=INSTITUTIONAL_OWNERSHIP_CHOICES, default='Any')
    
